-- CreateTable
CREATE TABLE "Cat" (
    "id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "wind" TEXT NOT NULL,
    "personality" TEXT NOT NULL,
    "appearance" TEXT[],
    "clothes" TEXT[],
    "birthYear" INTEGER NOT NULL,
    "birthSeason" "Season" NOT NULL,
    "birthDay" INTEGER NOT NULL,
    "pronouns" TEXT NOT NULL,
    "origin" TEXT NOT NULL,
    "species" TEXT NOT NULL,
    "sizeLb" INTEGER NOT NULL,
    "sizeKg" INTEGER NOT NULL,
    "fur" TEXT NOT NULL,
    "color" TEXT NOT NULL,
    "pattern" TEXT NOT NULL,
    "whiteMarks" TEXT NOT NULL,
    "eyeColor" TEXT NOT NULL,
    "heldTrinket" INTEGER NOT NULL,
    "job" TEXT NOT NULL,
    "class" TEXT NOT NULL,
    "strength" INTEGER NOT NULL,
    "agility" INTEGER NOT NULL,
    "health" INTEGER NOT NULL,
    "finesse" INTEGER NOT NULL,
    "cleverness" INTEGER NOT NULL,
    "perception" INTEGER NOT NULL,
    "luck" INTEGER NOT NULL,
    "bravery" INTEGER NOT NULL,
    "benevolence" INTEGER NOT NULL,
    "energy" INTEGER NOT NULL,
    "extroversion" INTEGER NOT NULL,
    "dedication" INTEGER NOT NULL,
    "friends" JSONB NOT NULL,
    "family" JSONB NOT NULL,

    CONSTRAINT "Cat_pkey" PRIMARY KEY ("id")
);
